const isHyper = process.env.TERM_PROGRAM === "Hyper";
const isWindows = process.platform === "win32";
const isLinux = process.platform === "linux";

export const ballotDisabled = "☒";
export const ballotOff = "☐";
export const ballotOn = "☑";
export const bullet = "•";
export const bulletWhite = "◦";
export const fullBlock = "█";
export const heart = "❤";
export const identicalTo = "≡";
export const line = "─";
export const mark = "※";
export const middot = "·";
export const minus = "－";
export const multiplication = "×";
export const obelus = "÷";
export const pencilDownRight = "✎";
export const pencilRight = "✏";
export const pencilUpRight = "✐";
export const percent = "%";
export const pilcrow2 = "❡";
export const pilcrow = "¶";
export const plusMinus = "±";
export const section = "§";
export const starsOff = "☆";
export const starsOn = "★";
export const upDownArrow = "↕";

export const check = isWindows && !isHyper ? "√" : "✔";
export const cross = isWindows && !isHyper ? "×" : "✖";
export const ellipsisLarge = isWindows && !isHyper ? "..." : "⋯";
export const ellipsis = isWindows && !isHyper ? "..." : "…";
export const info = isWindows && !isHyper ? "i" : "ℹ";
export const question = isWindows && !isHyper ? "?" : "?";
export const questionSmall = isWindows && !isHyper ? "?" : "﹖";
export const pointer = isWindows && !isHyper ? ">" : isLinux ? "▸" : "❯";
export const pointerSmall = isWindows && !isHyper ? "»" : isLinux ? "‣" : "›";
export const radioOff = isWindows && !isHyper ? "( )" : "◯";
export const radioOn = isWindows && !isHyper ? "(*)" : "◉";
export const warning = isWindows && !isHyper ? "‼" : "⚠";
